### ISSUE TITLE
Error when using splithalf(): "No suitable data supplied" for eempf_ssc(). 

### ISSUE THREAD

**Issue by TRMattHarris** [MatthiasPucher/staRdom#13] opened 2020-07-07 01:19 UTC
Hi Matthias! Terrific package, I've been using staRdom to completely eliminate my lab's need for expensive standalone software. 

I've been trying to run some split-half analyses, but the function just doesn't seem to like the PARAFAC models when it comes time to generate the shift-and shape-sensitive congruence. 

Here's the error I get:
"Error in eempf_ssc(pfmodels = ., tcc = tcc, m = m, cores = cores) : 
  No suitable data supplied! Please refer to the eempf_ssc help."

I am certain I'm using either the output of a split-half, or a set of PARAFAC models supplied in the list output from eem_parafac(). It also fails for the same reason when using the eem_list example in the doc. Any idea what the issue is?

**Comment by liberty0117** [comment] 2020-07-12 10:55
I have the same problem.

**Comment by MatthiasPucher** [comment] 2020-07-13 11:27
Thank you for leaving a comment.
I could not reproduce the problem so far. The current version on GitHub offers more information when you set verbose = TRUE.
This might help us to find out what the actual problem is. Any more information you have would be welcome!

**Comment by MatthiasPucher** [comment] 2020-07-24 13:44
The issue is fixed in the current GitHub version. It was related to a switch to R 4.0. I will check the whole package with R 4.0 within the next days and send a complete update to CRAN afterwards. So far, the GitHub version should do its job.

**Closed by MatthiasPucher** 2020-07-24 13:44 UTC
